# Generated by Django 5.2.4 on 2025-07-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], max_length=10)),
                ('category', models.CharField(choices=[('public', 'Public'), ('commercial', 'Commercial'), ('residential', 'Residential'), ('landmark', 'Landmark'), ('urbanism', 'Urbanism')], max_length=20)),
                ('location', models.CharField(choices=[('scandinavia', 'Scandinavia'), ('eastern-europe', 'Eastern Europe'), ('central-europe', 'Central Europe'), ('baltic-countries', 'Baltic Countries'), ('middle-east', 'Middle East')], max_length=30)),
                ('image_main', models.ImageField(upload_to='images/projects/')),
                ('image_alt1', models.ImageField(upload_to='images/projects/')),
                ('image_alt2', models.ImageField(upload_to='images/projects/')),
            ],
        ),
    ]
