# Generated by Django 5.2.4 on 2025-07-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption10',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_caption9',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_img1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_img10',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_img2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_img3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_img4',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_img5',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_img6',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_img7',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_img8',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_img9',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/intro/'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='slideshow_1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/slideshow/'),
        ),
        migrations.AddField(
            model_name='project',
            name='slideshow_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/slideshow/'),
        ),
        migrations.AddField(
            model_name='project',
            name='slideshow_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/slideshow/'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('commercial', 'Commercial'), ('residential', 'Residential'), ('landmark', 'Landmark'), ('urbanism', 'Urbanism')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_alt1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_alt2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_main',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
