# Generated by Django 5.2.4 on 2025-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_project_client_project_gallery_caption1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('public', 'Public'), ('commercial', 'Commercial'), ('residential', 'Residential'), ('landmark', 'Landmark'), ('urbanism', 'Urbanism')], max_length=50),
        ),
    ]
