# Generated by Django 5.2.4 on 2025-07-31 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('public', 'Public'), ('commercial', 'Commercial'), ('residential', 'Residential'), ('landmark', 'Landmark'), ('urbanism', 'Urbanism')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('scandinavia', 'Scandinavia'), ('central-europe', 'Central Europe'), ('baltic', 'Baltic Countries'), ('eastern-europe', 'Eastern Europe'), ('middle-east', 'Middle East')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='gallery.project')),
            ],
        ),
    ]
