# Generated by Django 5.2.4 on 2025-08-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_project_country_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
