# Generated by Django 5.2.4 on 2025-08-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_project_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gallery_caption1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_caption10',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_caption2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_caption3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_caption4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_caption5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_caption6',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_caption7',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_caption8',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_caption9',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_img1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_img10',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_img2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_img3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_img4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_img5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_img6',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_img7',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_img8',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_img9',
        ),
    ]
