# Generated by Django 5.2.4 on 2025-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.TextField(blank=True, null=True),
        ),
    ]
