# Generated by Django 5.2.4 on 2025-08-25 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_project_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sidebar_order', models.PositiveIntegerField(default=1)),
                ('index_number', models.CharField(default='01', max_length=4)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('highlight', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('image_layout', models.CharField(choices=[('one', 'One image'), ('three', 'Three images')], default='three', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sidebar_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='research/')),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('position', models.PositiveIntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.researcharticle')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
