# Generated by Django 5.2.4 on 2025-08-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_researcharticle_researchimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcharticle',
            name='image_layout',
            field=models.CharField(choices=[('three', 'Standard layout')], default='three', max_length=10),
        ),
    ]
