# Generated by Django 5.2.4 on 2025-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_researcharticle_image_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcharticle',
            name='image_layout',
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='article_layout',
            field=models.CharField(choices=[('short', 'Short layout'), ('long', 'Long layout')], default='short', max_length=10),
        ),
    ]
