# Generated by Django 5.2.4 on 2025-08-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_remove_researcharticle_image_layout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='research/')),
                ('position', models.PositiveIntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='gallery.researcharticle')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
