# Generated by Django 5.2.4 on 2025-08-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_researchblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcharticle',
            name='highlight',
        ),
    ]
