# Generated by Django 5.2.4 on 2025-08-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_remove_researcharticle_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchblock',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchblock',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
