# Generated by Django 5.2.4 on 2025-08-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_alter_researchblock_text_alter_researchblock_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcharticle',
            old_name='subtitle',
            new_name='date',
        ),
        migrations.AddField(
            model_name='researchblock',
            name='layout_type',
            field=models.CharField(choices=[('layout_a', 'Image left + text + 2 small images'), ('layout_b', 'Image right + text'), ('layout_c', 'Row of 4 images'), ('layout_d', 'Text only')], default='layout_a', max_length=20),
        ),
    ]
