# Generated by Django 5.2.4 on 2025-08-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_rename_subtitle_researcharticle_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchblock',
            name='image',
        ),
        migrations.AddField(
            model_name='researchblock',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Primary / hero', null=True, upload_to='research/'),
        ),
        migrations.AddField(
            model_name='researchblock',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Secondary', null=True, upload_to='research/'),
        ),
        migrations.AddField(
            model_name='researchblock',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Tertiary', null=True, upload_to='research/'),
        ),
        migrations.AddField(
            model_name='researchblock',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Quaternary', null=True, upload_to='research/'),
        ),
        migrations.AlterField(
            model_name='researchblock',
            name='layout_type',
            field=models.CharField(choices=[('layout_a', 'A · Hero + two small'), ('layout_b', 'B · Single hero'), ('layout_c', 'C · Four in a row'), ('layout_d', 'D · Text only')], default='layout_b', max_length=20),
        ),
    ]
