# Generated by Django 5.2.4 on 2025-10-01 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_remove_researchblock_image_researchblock_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_main',
            field=models.FileField(upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'mp4', 'webm', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('scandinavia', 'Scandinavia'), ('central-europe', 'Central Europe'), ('middle-east', 'Middle East')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='image',
            field=models.FileField(upload_to='projects/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'mp4', 'webm', 'mov'])]),
        ),
    ]
