# Generated by Django 5.2.4 on 2025-10-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_alter_project_image_main_alter_project_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='intro_image',
        ),
    ]
