# Generated by Django 5.2.4 on 2025-10-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_remove_project_intro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('commercial', 'Commercial'), ('residential', 'Residential'), ('landmark', 'Landmark'), ('urbanism', 'Urbanism')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, choices=[('scandinavia', 'Scandinavia'), ('central-europe', 'Central Europe'), ('middle-east', 'Middle East')], max_length=20, null=True),
        ),
    ]
